/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedResidentsRouteImport } from './routes/_authenticated/residents'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMyRequestsRouteImport } from './routes/_authenticated/my-requests'
import { Route as AuthenticatedMyInstallmentsRouteImport } from './routes/_authenticated/my-installments'
import { Route as AuthenticatedInstallmentsRouteImport } from './routes/_authenticated/installments'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedResidentsResidentIdRouteImport } from './routes/_authenticated/residents.$residentId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResidentsRoute = AuthenticatedResidentsRouteImport.update({
  id: '/residents',
  path: '/residents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMyRequestsRoute = AuthenticatedMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMyInstallmentsRoute =
  AuthenticatedMyInstallmentsRouteImport.update({
    id: '/my-installments',
    path: '/my-installments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInstallmentsRoute =
  AuthenticatedInstallmentsRouteImport.update({
    id: '/installments',
    path: '/installments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResidentsResidentIdRoute =
  AuthenticatedResidentsResidentIdRouteImport.update({
    id: '/$residentId',
    path: '/$residentId',
    getParentRoute: () => AuthenticatedResidentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/installments': typeof AuthenticatedInstallmentsRoute
  '/my-installments': typeof AuthenticatedMyInstallmentsRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/residents': typeof AuthenticatedResidentsRouteWithChildren
  '/services': typeof AuthenticatedServicesRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/residents/$residentId': typeof AuthenticatedResidentsResidentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/installments': typeof AuthenticatedInstallmentsRoute
  '/my-installments': typeof AuthenticatedMyInstallmentsRoute
  '/my-requests': typeof AuthenticatedMyRequestsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/residents': typeof AuthenticatedResidentsRouteWithChildren
  '/services': typeof AuthenticatedServicesRoute
  '/units': typeof AuthenticatedUnitsRoute
  '/residents/$residentId': typeof AuthenticatedResidentsResidentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/installments': typeof AuthenticatedInstallmentsRoute
  '/_authenticated/my-installments': typeof AuthenticatedMyInstallmentsRoute
  '/_authenticated/my-requests': typeof AuthenticatedMyRequestsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/_authenticated/residents': typeof AuthenticatedResidentsRouteWithChildren
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRoute
  '/_authenticated/residents/$residentId': typeof AuthenticatedResidentsResidentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/announcements'
    | '/dashboard'
    | '/employees'
    | '/installments'
    | '/my-installments'
    | '/my-requests'
    | '/notifications'
    | '/projects'
    | '/requests'
    | '/residents'
    | '/services'
    | '/units'
    | '/residents/$residentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/announcements'
    | '/dashboard'
    | '/employees'
    | '/installments'
    | '/my-installments'
    | '/my-requests'
    | '/notifications'
    | '/projects'
    | '/requests'
    | '/residents'
    | '/services'
    | '/units'
    | '/residents/$residentId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/announcements'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/installments'
    | '/_authenticated/my-installments'
    | '/_authenticated/my-requests'
    | '/_authenticated/notifications'
    | '/_authenticated/projects'
    | '/_authenticated/requests'
    | '/_authenticated/residents'
    | '/_authenticated/services'
    | '/_authenticated/units'
    | '/_authenticated/residents/$residentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residents': {
      id: '/_authenticated/residents'
      path: '/residents'
      fullPath: '/residents'
      preLoaderRoute: typeof AuthenticatedResidentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-requests': {
      id: '/_authenticated/my-requests'
      path: '/my-requests'
      fullPath: '/my-requests'
      preLoaderRoute: typeof AuthenticatedMyRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/my-installments': {
      id: '/_authenticated/my-installments'
      path: '/my-installments'
      fullPath: '/my-installments'
      preLoaderRoute: typeof AuthenticatedMyInstallmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/installments': {
      id: '/_authenticated/installments'
      path: '/installments'
      fullPath: '/installments'
      preLoaderRoute: typeof AuthenticatedInstallmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/residents/$residentId': {
      id: '/_authenticated/residents/$residentId'
      path: '/$residentId'
      fullPath: '/residents/$residentId'
      preLoaderRoute: typeof AuthenticatedResidentsResidentIdRouteImport
      parentRoute: typeof AuthenticatedResidentsRoute
    }
  }
}

interface AuthenticatedResidentsRouteChildren {
  AuthenticatedResidentsResidentIdRoute: typeof AuthenticatedResidentsResidentIdRoute
}

const AuthenticatedResidentsRouteChildren: AuthenticatedResidentsRouteChildren =
  {
    AuthenticatedResidentsResidentIdRoute:
      AuthenticatedResidentsResidentIdRoute,
  }

const AuthenticatedResidentsRouteWithChildren =
  AuthenticatedResidentsRoute._addFileChildren(
    AuthenticatedResidentsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedInstallmentsRoute: typeof AuthenticatedInstallmentsRoute
  AuthenticatedMyInstallmentsRoute: typeof AuthenticatedMyInstallmentsRoute
  AuthenticatedMyRequestsRoute: typeof AuthenticatedMyRequestsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
  AuthenticatedResidentsRoute: typeof AuthenticatedResidentsRouteWithChildren
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedInstallmentsRoute: AuthenticatedInstallmentsRoute,
  AuthenticatedMyInstallmentsRoute: AuthenticatedMyInstallmentsRoute,
  AuthenticatedMyRequestsRoute: AuthenticatedMyRequestsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
  AuthenticatedResidentsRoute: AuthenticatedResidentsRouteWithChildren,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
